
source = ~/.config/hypr/vars.conf

exec-once = clipse -listen

#Rules for window manager
windowrulev2 = float, class:(clipse)
windowrulev2 = size 622 652, class:(clipse)
windowrulev2 = stayfocused, class:(clipse)

bind = $mainMod, V, exec, $terminal --class clipse -e clipse