
$rosewaterHex   =   f2d5cf
$flamingoHex    =   eebebe
$pinkHex        =   f4b8e4
$mauveHex       =   ca9ee6
$redHex         =   e78284
$maroonHex      =   ea999c
$peachHex       =   ef9f76
$yellowHex      =   e5c890
$greenHex       =   a6d189
$tealHex        =   81c8be
$skyHex         =   99d1db
$sapphireHex    =   85c1dc
$blueHex        =   8caaee
$lavenderHex    =   babbf1
$textHex        =   c6d0f5
$subtext1Hex    =   b5bfe2
$subtext0Hex    =   a5adce
$overlay2Hex    =   949cbb
$overlay1Hex    =   838ba7
$overlay0Hex    =   737994
$surface2Hex    =   626880
$surface1Hex    =   51576d
$surface0Hex    =   414559
$baseHex        =   303446
$mantleHex      =   292c3c
$crustHex       =   232634


$rosewater      =   rgb($rosewaterHex)
$flamingo       =   rgb($flamingoHex)
$pink           =   rgb($pinkHex)
$mauve          =   rgb($mauveHex)
$red            =   rgb($redHex)
$maroon         =   rgb($maroonHex)
$peach          =   rgb($peachHex)
$yellow         =   rgb($yellowHex)
$green          =   rgb($greenHex)
$teal           =   rgb($tealHex)
$sky            =   rgb($skyHex)
$sapphire       =   rgb($sapphireHex)
$blue           =   rgb($blueHex)
$lavender       =   rgb($lavenderHex)
$text           =   rgb($textHex)
$subtext1       =   rgb($subtext1Hex)
$subtext0       =   rgb($subtext0Hex)
$overlay2       =   rgb($overlay2Hex)
$overlay1       =   rgb($overlay1Hex)
$overlay0       =   rgb($overlay0Hex)
$surface2       =   rgb($surface2Hex)
$surface1       =   rgb($surface1Hex)
$surface0       =   rgb($surface0Hex)
$base           =   rgb($baseHex)
$mantle         =   rgb($mantleHex)
$crust          =   rgb($crustHex)

$accent         =   $peach
$accentHex      =   $peachHex