
#################
### VARIABLES ###
#################

source = ./vars.conf

###############
### DEVICES ###
###############

source = ./devices.conf

##############
### RICING ###
##############

source = ./looks.conf

#############
### BINDS ###
#############

source = ./binds.conf
source = ./gestures.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ./workspaces.conf

###################
### MY PROGRAMS ###
###################

#source = ~/.config/hypr/hints.conf

#######source = ./clipse.conf

#source = ~/.config/hypr/hyprswitch.conf

#################
### AUTOSTART ###
#################

# Also see files for individual applications

# Hyprpaper
exec = pidof -q hyprpaper || hyprpaper 

# Hypridle
exec = pidof -q hypridle || hypridle

# Batsignal
exec = pidof -q batsignal || batsignal -eb

# Inhibit idle when playing audio, restarting is done in "~/.config/hypr/reloadAll.sh"
exec-once = sway-audio-idle-inhibit

# Polkit
exec = pidof -q hyprpolkitagent || systemctl --user start hyprpolkitagent

# Syshud
exec = pidof -q syshud || syshud

# Hyprshell
#exec-once = hyprshell run &

# EasyEffects
exec-once = easyeffects --gapplication-service

# Network Manager tray applet
exec-once = nm-applet --indicator

# KDEconnect daemon
exec-once = /usr/bin/kdeconnectd
exec-once = kdeconnect-indicator
exec = kdeconnect-cli --refresh

# Waybar
exec-once = waybar
exec-once = waybar -c /home/erogig/.config/waybar/clock.jsonc -s /home/erogig/.config/waybar/clock.css

# Bitwarden tray icon
exec-once = bitwarden-desktop

# Workplaces
exec = [workspace name:discord silent] pidof -q $discordClient || $discordClient 
exec = [workspace name:browser silent] pidof -q $webBrowser || $webBrowser
exec = [workspace name:music silent] pidof -q rmpc || kitty --class rmpc -e rmpc
# exec = [workspace name:top silent] pidof -q btop || kitty --class btop -e btop
exec = [workspace name:steam silent] pidof -q steam || steam

exec = pidof -q mpd-mpris || mpd-mpris -host "/home/erogig/.config/mpd/socket" -network unix

#############################
### ENVIRONMENT VARIABLES ###
#############################

# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# GPU prio
# env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

# Fix Electron
env = ELECTRON_OZONE_PLATFORM_HINT, wayland

# XDG
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# GTK
# env = GDK_BACKEND,wayland,x11,*

# QT
# env = QT_AUTO_SCREEN_SCALE_FACTOR,1
# env = QT_QPA_PLATFORM,wayland;xcb
# env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
# env = QT_QPA_PLATFORMTHEME,qt6ct
# env = QT_STYLE_OVERRIDE,kvantum

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    layers_hog_keyboard_focus = false
    font_family = Inter
}
