
$hyprDir = "/home/erogig/.config/hypr/hyprland/"

$terminal = kitty
$webBrowser = floorp
$fileManager = dolphin
$menu = rofi
$discordClient = vesktop

#$menu = $createChildren -p "wofi --show drun" -c "waybar"

$mainMod = super 
