
###############
### COLOURS ###
###############

source = ~/.config/hypr/colours.conf

###############
### DEVICES ###
###############

source = ~/.config/hypr/devices.conf

general {
}

auth {
    fingerprint:enabled = true
}

background {
    monitor = 
        path = screenshot

    blur_size = 5
    blur_passes = 1 # 0 disables blurring
    noise = 0.0117
    #contrast = 1.3000 # Vibrant!!!
    brightness = 0.4000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true

    outer_color = $surface0
    inner_color = $crust
    font_color = $text
    check_color = $surface0
    fail_color = $red

    fade_on_empty = true
    fade_timeout = 1000

    placeholder_text = <i>...</i>

    position = 0, -100
    halign = center
    valign = center
}

#Time
label {
    monitor =
    #text = cmd[update:1000] echo "<b><big> $(date +"%I:%M:%S %p") </big></b>" # AM/PM
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>" # 24H
    color = $text
    font_size = 94
    font_family = AdwaitaMonoNFM

    position = 0, 0
    halign = center
    valign = center
}

#User
label {
    monitor =
    text =    $USER
    color = $text
    font_size = 18
    font_family = AdwaitaMonoNFM

    position = 0, 100
    halign = center
    valign = bottom
}