
source = ~/.config/hypr/vars.conf

$hints = ~/.local/bin/hints

# Enable accesssibility
env = ACCESSIBILITY_ENABLED, 1
env = GTK_MODULES,gail:atk-bridge
env = OOO_FORCE_DESKTOP,gnome
env = GNOME_ACCESSIBILITY,1
env = QT_ACCESSIBILITY,1
env = QT_LINUX_ACCESSIBILITY_ALWAYS_ON,1

# availible as deamon (didn't seem to start though :( )
exec-once = ~/.local/bin/hintsd

bind = $mainMod, space, exec, $hints
bind = Mod5, space, exec, $hints --mode scroll