
source = ~/.config/hypr/vars.conf

bind = alt, tab, exec, hyprswitch simple --sort-recent

#bind = alt, tab, exec, hyprswitch gui --mod-key $mainMod --key tab --close mod-key-release --reverse-key=mod=shift_l -w
#bind = $mainMod shift_l, tab, exec, hyprswitch gui --mod-key $mainMod --key tab --close mod-key-release --reverse-key=mod=shift_l -w
